name: droll

# The packages we (may) depend on
dependencies:
  - base             # For built-in functions like `length`
  - containers       # For Data.Map, etc., if needed
  - text             # For Data.Text, if needed
  - mtl              # For Control.Monad.*, if needed
  - parsec           # If needed; ReadP is already part of base
  - random           # Used by Driver only
  # Don't add anything else here

# The Droll libraries
library:
  source-dirs: src
  ghc-options:
    - -W
  exposed-modules:
    - Types
    - Parser
    - Calculator

executable:
  source-dirs:
    - src
    - app
  main: Main.hs

# Sample test suite
tests:
  primary-test-suite:
    main: BlackBox.hs
    source-dirs: tests
    dependencies:
      - droll
      - tasty
      - tasty-hunit
      - QuickCheck       # if you want to use it
      - tasty-quickcheck # ditto
      # Don't add anything else here
#  other-test-suite:
#    main: WhiteBox.hs
#    source-dirs: [tests/suite1, src]
#    dependencies:
#      - droll
#      - tasty
#      - tasty-hunit
#      # Whatever else you need from the exam LTS version
